# Create a namespace for the OpenShift Elasticsearch Operator
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: gitops-service-argocd
    openshift.io/cluster-monitoring: "true"
---

# Create a namespace for the Red Hat OpenShift Logging Operator
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""  
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: gitops-service-argocd
    openshift.io/cluster-monitoring: "true"
---

# Install the OpenShift Elasticsearch Operator
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat 
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec: {}
---

# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: "elasticsearch-operator"
#   namespace: "openshift-operators-redhat"
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   channel: "stable-5.5" 
#   installPlanApproval: "Automatic" 
#   source: "redhat-operators" 
#   sourceNamespace: "openshift-marketplace"
#   name: "elasticsearch-operator"
---

# Install the Red Hat OpenShift Logging Operator
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-logging
  namespace: openshift-logging 
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  targetNamespaces:
  - openshift-logging 
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: "stable" 
  name: cluster-logging
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
